/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/jugadores/buscar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar Jugador */
        get: operations["buscar_jugador_api_v1_jugadores_buscar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jugadores/{player_id}/estadisticas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Estadisticas */
        get: operations["obtener_estadisticas_api_v1_jugadores__player_id__estadisticas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jugadores/{player_id}/valor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Predecir Valor */
        get: operations["predecir_valor_api_v1_jugadores__player_id__valor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jugadores/{player_id}/percentiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Percentiles */
        get: operations["obtener_percentiles_api_v1_jugadores__player_id__percentiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jugadores/{player_id}/arquetipo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Arquetipo */
        get: operations["obtener_arquetipo_api_v1_jugadores__player_id__arquetipo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jugadores/{player_id}/historial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Historial */
        get: operations["obtener_historial_api_v1_jugadores__player_id__historial_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jugadores/{player_id}/ficha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Ficha
         * @description Combina los 5 endpoints anteriores en una sola llamada (conveniencia de Fase 1).
         */
        get: operations["obtener_ficha_api_v1_jugadores__player_id__ficha_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArquetipoJugador */
        ArquetipoJugador: {
            /** Cluster Id */
            cluster_id: number;
            /** Etiqueta */
            etiqueta: string;
        };
        /** BandaValor */
        BandaValor: {
            /** Valor Bajo */
            valor_bajo: number;
            /** Valor Medio */
            valor_medio: number;
            /** Valor Alto */
            valor_alto: number;
            /**
             * Moneda
             * @default EUR
             */
            moneda: string;
        };
        /** ContribucionVariable */
        ContribucionVariable: {
            /** Feature */
            feature: string;
            /** Etiqueta */
            etiqueta: string;
            /** Contribucion Log */
            contribucion_log: number;
            /** Valor Bruto Jugador */
            valor_bruto_jugador: number;
            /** Direccion */
            direccion: string;
        };
        /** EstadisticasJugador */
        EstadisticasJugador: {
            /** Player Id */
            player_id: string;
            /** Nombre */
            nombre: string;
            /** Club */
            club: string;
            /** Nacionalidad */
            nacionalidad: string;
            /** Posicion */
            posicion: string;
            /** Posicion Detallada */
            posicion_detallada: string;
            /** Liga */
            liga: string;
            /** Temporada */
            temporada: string;
            /** Edad */
            edad: number;
            /** Minutos Jugados */
            minutos_jugados: number;
            /** Goles */
            goles: number;
            /** Asistencias */
            asistencias: number;
            /** Tiros */
            tiros: number;
            /** Tarjetas Amarillas */
            tarjetas_amarillas: number;
            /** Valor Mercado Eur */
            valor_mercado_eur: number;
            /** Contrato Conocido */
            contrato_conocido: boolean;
            /** Dias Contrato Restante */
            dias_contrato_restante: number | null;
            /** Gano Liga */
            gano_liga: boolean;
            /** Gano Champions */
            gano_champions: boolean;
        };
        /** GrupoComparacion */
        GrupoComparacion: {
            /** Posicion */
            posicion: string;
            /** Temporada */
            temporada: string;
            /** N */
            n: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistorialJugador */
        HistorialJugador: {
            /** Player Id */
            player_id: string;
            /** Nombre */
            nombre: string;
            /** Temporadas */
            temporadas: components["schemas"]["TemporadaRendimiento"][];
        };
        /** JugadorBusqueda */
        JugadorBusqueda: {
            /** Player Id */
            player_id: string;
            /** Nombre */
            nombre: string;
            /** Club */
            club: string;
            /** Posicion */
            posicion: string;
            /** Liga */
            liga: string;
            /** Temporada Mas Reciente */
            temporada_mas_reciente: string;
        };
        /** PercentilEstadistica */
        PercentilEstadistica: {
            /** Estadistica */
            estadistica: string;
            /** Etiqueta */
            etiqueta: string;
            /** Percentil */
            percentil: number;
            /** Valor Bruto */
            valor_bruto: number;
        };
        /** PercentilesJugador */
        PercentilesJugador: {
            grupo_comparacion: components["schemas"]["GrupoComparacion"];
            /** Percentiles */
            percentiles: components["schemas"]["PercentilEstadistica"][];
        };
        /** PrediccionValor */
        PrediccionValor: {
            banda: components["schemas"]["BandaValor"];
            /** Contribuciones */
            contribuciones: components["schemas"]["ContribucionVariable"][];
            /**
             * Metodologia Nota
             * @default Estimación de un modelo estadístico entrenado con datos históricos de rendimiento y valor de mercado. No es una tasación oficial ni una recomendación de compra o venta: preséntese siempre como rango, nunca como cifra puntual.
             */
            metodologia_nota: string;
        };
        /** TemporadaRendimiento */
        TemporadaRendimiento: {
            /** Temporada */
            temporada: string;
            /** Saison Id */
            saison_id: number;
            /** Club */
            club: string;
            /** Goles */
            goles: number;
            /** Tiros */
            tiros: number;
            /** Tarjetas Amarillas */
            tarjetas_amarillas: number;
            /** Asistencias */
            asistencias: number;
            /** Valor Mercado Eur */
            valor_mercado_eur: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    buscar_jugador_api_v1_jugadores_buscar_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JugadorBusqueda"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_estadisticas_api_v1_jugadores__player_id__estadisticas_get: {
        parameters: {
            query?: {
                temporada?: number | null;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadisticasJugador"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predecir_valor_api_v1_jugadores__player_id__valor_get: {
        parameters: {
            query?: {
                temporada?: number | null;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrediccionValor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_percentiles_api_v1_jugadores__player_id__percentiles_get: {
        parameters: {
            query?: {
                temporada?: number | null;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PercentilesJugador"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_arquetipo_api_v1_jugadores__player_id__arquetipo_get: {
        parameters: {
            query?: {
                temporada?: number | null;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquetipoJugador"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_historial_api_v1_jugadores__player_id__historial_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistorialJugador"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_ficha_api_v1_jugadores__player_id__ficha_get: {
        parameters: {
            query?: {
                temporada?: number | null;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
